// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/volume/volume.proto

package volume

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Volume service

func NewVolumeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Volume service

type VolumeService interface {
	//对外提供添加服务
	AddVolume(ctx context.Context, in *VolumeInfo, opts ...client.CallOption) (*Response, error)
	DeleteVolume(ctx context.Context, in *VolumeId, opts ...client.CallOption) (*Response, error)
	UpdateVolume(ctx context.Context, in *VolumeInfo, opts ...client.CallOption) (*Response, error)
	FindVolumeByID(ctx context.Context, in *VolumeId, opts ...client.CallOption) (*VolumeInfo, error)
	FindAllVolume(ctx context.Context, in *FindAll, opts ...client.CallOption) (*AllVolume, error)
}

type volumeService struct {
	c    client.Client
	name string
}

func NewVolumeService(name string, c client.Client) VolumeService {
	return &volumeService{
		c:    c,
		name: name,
	}
}

func (c *volumeService) AddVolume(ctx context.Context, in *VolumeInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Volume.AddVolume", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeService) DeleteVolume(ctx context.Context, in *VolumeId, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Volume.DeleteVolume", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeService) UpdateVolume(ctx context.Context, in *VolumeInfo, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Volume.UpdateVolume", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeService) FindVolumeByID(ctx context.Context, in *VolumeId, opts ...client.CallOption) (*VolumeInfo, error) {
	req := c.c.NewRequest(c.name, "Volume.FindVolumeByID", in)
	out := new(VolumeInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeService) FindAllVolume(ctx context.Context, in *FindAll, opts ...client.CallOption) (*AllVolume, error) {
	req := c.c.NewRequest(c.name, "Volume.FindAllVolume", in)
	out := new(AllVolume)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Volume service

type VolumeHandler interface {
	//对外提供添加服务
	AddVolume(context.Context, *VolumeInfo, *Response) error
	DeleteVolume(context.Context, *VolumeId, *Response) error
	UpdateVolume(context.Context, *VolumeInfo, *Response) error
	FindVolumeByID(context.Context, *VolumeId, *VolumeInfo) error
	FindAllVolume(context.Context, *FindAll, *AllVolume) error
}

func RegisterVolumeHandler(s server.Server, hdlr VolumeHandler, opts ...server.HandlerOption) error {
	type volume interface {
		AddVolume(ctx context.Context, in *VolumeInfo, out *Response) error
		DeleteVolume(ctx context.Context, in *VolumeId, out *Response) error
		UpdateVolume(ctx context.Context, in *VolumeInfo, out *Response) error
		FindVolumeByID(ctx context.Context, in *VolumeId, out *VolumeInfo) error
		FindAllVolume(ctx context.Context, in *FindAll, out *AllVolume) error
	}
	type Volume struct {
		volume
	}
	h := &volumeHandler{hdlr}
	return s.Handle(s.NewHandler(&Volume{h}, opts...))
}

type volumeHandler struct {
	VolumeHandler
}

func (h *volumeHandler) AddVolume(ctx context.Context, in *VolumeInfo, out *Response) error {
	return h.VolumeHandler.AddVolume(ctx, in, out)
}

func (h *volumeHandler) DeleteVolume(ctx context.Context, in *VolumeId, out *Response) error {
	return h.VolumeHandler.DeleteVolume(ctx, in, out)
}

func (h *volumeHandler) UpdateVolume(ctx context.Context, in *VolumeInfo, out *Response) error {
	return h.VolumeHandler.UpdateVolume(ctx, in, out)
}

func (h *volumeHandler) FindVolumeByID(ctx context.Context, in *VolumeId, out *VolumeInfo) error {
	return h.VolumeHandler.FindVolumeByID(ctx, in, out)
}

func (h *volumeHandler) FindAllVolume(ctx context.Context, in *FindAll, out *AllVolume) error {
	return h.VolumeHandler.FindAllVolume(ctx, in, out)
}
